### ISSUE TITLE
开源项目推荐: 2019nCoV

### ISSUE THREAD

**Issue by green512** [WeileiZeng/OpenSourceWuhan#3]
[2019nCoV](https://github.com/green512/2019nCoV) 2019-nCoV 疫情可视化

**其他留言**
本项目基于echart制作了随时间变化的全国地级市疫情热力图,基于百度地图制作了全球新冠肺炎疫情散点图和北京、上海、天津市确诊病例活动区域图，为新型冠状肺炎疫情的分析和个人健康防护服务。

**Comment by binjirouguang** [comment]
疫情热力图上显示北京天津的颜色这么红，与官方通报数据不符，有夸张之嫌

**Comment by green512** [comment]
> 疫情热力图上显示北京天津的颜色这么红，与官方通报数据不符，有夸张之嫌

热力图与分布密度有关系，北京和天津的统计单位为区县级，相对空间比较密集，使得热力图上显示的颜色比较红，已经改为散点图显示。
谢谢提醒。

**Comment by WeileiZeng** [comment]
谢谢！已收录！
