### ISSUE TITLE
开源项目推荐: COVID-19 Outbreak

### ISSUE THREAD

**Issue by liu-zoe** [WeileiZeng/OpenSourceWuhan#8]
[仓库名称]  wuhancv
(仓库链接)  https://github.com/liu-zoe/wuhancv
[项目名称] COVID-19 Outbreak
(项目网站链接) http://wh2019-ncov.herokuapp.com/
项目描述
A time lapse of bubble map showing number of confirmed cases of COVID-19 around the globe starting from Jan 22nd. Additionally, a time series plot presents cumulative count of confirmed, recovered, and deaths cases.

**Comment by WeileiZeng** [comment]
谢谢！已收录。
